server:
  port: 8003

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-cLass-name: com.mysql.jdbc.Driver
    url: jdbc:mysqL://LocaLhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GWT%2B8
    username: root
    password: pan1234
  thymeleaf:
    cache: false #thymeLeaf有缓存机制，去缓存
    mode: HTML5
    encoding: UTF-8
logging:
  level:
    com.pan: info
  file:
    path: "E:/springbootLog/test.Log"

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pan.pojo
  configuration:
    map-underscore-to-camel-case: true #识别驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置sqL打印
    cache-enabled: true
