bean-searcher:
  params:
    pagination:
      start: 1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/beansearchdb?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: pan1234
#初始化表
#  sql:
#    init:
#      username: root
#      password: pan1234
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
#      mode: always
#设置前后缀
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false

#设置日志打印
logging:
  pattern:
    console: "%d{HH:mm:ss} %-4level - %msg%n"



