server:
  port: 80

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: pan1234
  thymeleaf:
    cache: false #thymeleaf有缓存机制，去缓存
    mode: HTML5
    encoding: UTF-8

logging:
  level:
   com.pan: debug    #设置哪个包设置为debug级别
  path: "E:/springbootLog/test.log"

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pan.pojo
  configuration:
    map-underscore-to-camel-case: true  #识别驼峰命名法
