spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: pan1234
  data:
    solr:
      host: http://localhost:8983/solr
#      如果配置了账号信息使用右边 http://user1:pass1@localhost:8983/solr
